classes = {
        'assassin': {'hit_die' : 'd8',
            'ability minimums': {
                'strength': 12,
                'dexterity': 12,
                'intelligence': 9},
            'levels': {
                '1': {'min_xp': 0,
                    'num_proficiencies': 3},
                '10': {'base_attack_bonus': 6,
                    'min_xp': 300000},
                '11': {'min_xp': 425000},
                '12': {'base_attack_bonus': 7,
                    'min_xp': 575000},
                '13': {'min_xp': 750000,
                    'num_proficiencies': 6},
                '14': {'base_attack_bonus': 8,
                    'min_xp': 1000000},
                '15': {'base_attack_bonus': 9,
                    'min_xp': 1250000},
                '16': {'min_xp': 1500000},
                '17': {'base_attack_bonus': 10,
                    'min_xp': 1750000,
                    'num_proficiencies': 7},
                '18': {'min_xp': 2000000},
                '19': {'base_attack_bonus': 11,
                    'min_xp': 2250000},
                '2': {'base_attack_bonus': 1,
                    'min_xp': 1500},
                '20': {'base_attack_bonus': 12,
                    'min_xp': 2500000},
                '3': {'min_xp': 3000},
                '4': {'base_attack_bonus': 2,
                    'min_xp': 6000},
                '5': {'base_attack_bonus': 3,
                    'min_xp': 12000,
                    'num_proficiencies': 4},
                '6': {'min_xp': 25000},
                '7': {'base_attack_bonus': 4,
                    'min_xp': 50000},
                '8': {'min_xp': 100000},
                '9': {'base_attack_bonus': 5,
                    'min_xp': 200000,
                    'num_proficiencies': 5},
                'non_proficiency': '-2'}},
        'cleric': {'hit_die' : 'd8' ,
            'ability minimums': {
                'wisdom': 9},
            'levels': {'1': {'min_xp': 0,
                'num_proficiencies': 2},
                '10': {'min_xp': 450000},
                '11': {'base_attack_bonus': 5,
                    'min_xp': 675000},
                '12': {'min_xp': 900000},
                '13': {'base_attack_bonus': 6,
                    'min_xp': 1125000,
                    'num_proficiencies': 5},
                '14': {'min_xp': 1350000},
                '15': {'base_attack_bonus': 7,
                    'min_xp': 1575000},
                '16': {'min_xp': 1800000},
                '17': {'base_attack_bonus': 8,
                    'min_xp': 2025000,
                    'num_proficiencies': 6},
                '18': {'min_xp': 2250000},
                '19': {'min_xp': 2475000},
                '2': {'min_xp': 1500},
                '20': {'min_xp': 2700000},
                '3': {'base_attack_bonus': 1,
                    'min_xp': 3000},
                '4': {'min_xp': 6000},
                '5': {'base_attack_bonus': 2,
                    'min_xp': 13000,
                    'num_proficiencies': 3},
                '6': {'min_xp': 27500},
                '7': {'base_attack_bonus': 3,
                    'min_xp': 55000},
                '8': {'min_xp': 110000},
                '9': {'base_attack_bonus': 4,
                    'min_xp': 225000,
                    'num_proficiencies': 4}},
                'non_proficiency': '-3'},
        'druid': {'hit_die' : 'd8' ,
            'ability minimums': {
                'wisdom': 12,
                'charisma': 12},
                'levels': {'1': {'min_xp': 0,
                    'num_proficiencies': 2},
                    '10': {'min_xp': 150000},
                    '11': {'base_attack_bonus': 5,
                        'min_xp': 240000,
                        'num_proficiencies': 4},
                    '12': {'min_xp': 360000},
                    '13': {'base_attack_bonus': 6,
                        'min_xp': 540000},
                    '14': {'min_xp': 780000},
                    '15': {'base_attack_bonus': 7,
                        'min_xp': 1080000},
                    '16': {'min_xp': 1440000,
                        'num_proficiencies': 5},
                    '17': {'base_attack_bonus': 8,
                        'min_xp': 1800000},
                    '18': {'min_xp': 2160000},
                    '19': {'min_xp': 2520000},
                    '2': {'min_xp': 2400},
                    '20': {'min_xp': 2880000},
                    '3': {'base_attack_bonus': 1,
                        'min_xp': 4800},
                    '4': {'min_xp': 9000},
                    '5': {'base_attack_bonus': 2,
                        'min_xp': 15000},
                    '6': {'min_xp': 24000,
                        'num_proficiencies': 3},
                    '7': {'base_attack_bonus': 3,
                        'min_xp': 42000},
                    '8': {'min_xp': 72000},
                    '9': {'base_attack_bonus': 4,
                        'min_xp': 108000}},
                    'non_proficiency': '-4'},
        'fighter': {'hit_die' : 'd10',
            'ability minimums': {
                'strength': 12,
                'constitution': 9},
                'levels': {'1': {'base_attack_bonus': 1,
                    'min_xp': 0,
                    'num_proficiencies': 4},
                    '10': {'base_attack_bonus': 10,
                        'min_xp': 500000,
                        'num_proficiencies': 7},
                    '11': {'base_attack_bonus': 11,
                        'min_xp': 750000},
                    '12': {'base_attack_bonus': 12,
                        'min_xp': 1000000},
                    '13': {'base_attack_bonus': 13,
                        'min_xp': 1250000,
                        'num_proficiencies': 8},
                    '14': {'base_attack_bonus': 14,
                        'min_xp': 1500000},
                    '15': {'base_attack_bonus': 15,
                        'min_xp': 1750000},
                    '16': {'base_attack_bonus': 16,
                        'min_xp': 2000000,
                        'num_proficiencies': 9},
                    '17': {'min_xp': 2250000},
                    '18': {'min_xp': 2500000},
                    '19': {'min_xp': 2750000,
                        'num_proficiencies': 10},
                    '2': {'base_attack_bonus': 2,
                        'min_xp': 2000},
                    '20': {'min_xp': 3000000},
                    '3': {'base_attack_bonus': 3,
                        'min_xp': 4000},
                    '4': {'base_attack_bonus': 4,
                        'min_xp': 8000,
                        'num_proficiencies': 5},
                    '5': {'base_attack_bonus': 5,
                        'min_xp': 18000},
                    '6': {'base_attack_bonus': 6,
                        'min_xp': 35000},
                    '7': {'base_attack_bonus': 7,
                        'min_xp': 70000,
                        'num_proficiencies': 6},
                    '8': {'base_attack_bonus': 8,
                        'min_xp': 125000},
                    '9': {'base_attack_bonus': 9,
                        'min_xp': 250000}},
                    'non_proficiency': '-2'},
        'illusionist': {'hit_die' : 'd4',
            'ability minimums': {
                'dexterity': 9,
                'intelligence': 12},
                'levels': {'1': {'min_xp': 0,
                    'num_proficiencies': 1},
                    '10': {'min_xp': 220000},
                    '11': {'min_xp': 440000},
                    '12': {'min_xp': 660000},
                    '13': {'base_attack_bonus': 3,
                        'min_xp': 880000,
                        'num_proficiencies': 3},
                    '14': {'min_xp': 1100000},
                    '15': {'min_xp': 1320000},
                    '16': {'min_xp': 1540000},
                    '17': {'base_attack_bonus': 4,
                        'min_xp': 1760000},
                    '18': {'min_xp': 1980000},
                    '19': {'min_xp': 2200000,
                        'num_proficiencies': 4},
                    '2': {'min_xp': 2250},
                    '20': {'min_xp': 2420000},
                    '3': {'min_xp': 4500},
                    '4': {'min_xp': 9000},
                    '5': {'base_attack_bonus': 1,
                        'min_xp': 18000},
                    '6': {'min_xp': 35000},
                    '7': {'min_xp': 60000,
                        'num_proficiencies': 2},
                    '8': {'min_xp': 95000},
                    '9': {'base_attack_bonus': 2,
                        'min_xp': 145000}},
                    'non_proficiency': '-5'},
        'mage': {'hit_die' : 'd4',
            'ability minimums': {
                'intelligence': 9},
                'levels': {'1': {'min_xp': 0,
                    'num_proficiencies': 1},
                    '10': {'min_xp': 250000},
                    '11': {'min_xp': 375000},
                    '12': {'min_xp': 750000},
                    '13': {'base_attack_bonus': 3,
                        'min_xp': 1125000,
                        'num_proficiencies': 3},
                    '14': {'min_xp': 1500000},
                    '15': {'min_xp': 1875000},
                    '16': {'min_xp': 2250000},
                    '17': {'base_attack_bonus': 4,
                        'min_xp': 2625000},
                    '18': {'min_xp': 3000000},
                    '19': {'min_xp': 3375000,
                        'num_proficiencies': 4},
                    '2': {'min_xp': 2500},
                    '20': {'min_xp': 3750000},
                    '3': {'min_xp': 5000},
                    '4': {'min_xp': 10000},
                    '5': {'base_attack_bonus': 1,
                        'min_xp': 22500},
                    '6': {'min_xp': 40000},
                    '7': {'min_xp': 60000,
                        'num_proficiencies': 2},
                    '8': {'min_xp': 90000},
                    '9': {'base_attack_bonus': 2,
                        'min_xp': 135000}},
                    'non_proficiency': '-5'},
        'monk': {'hit_die' : 'd6',
            'ability minimums': {
                'strength': 12,
                'constitution': 12,
                'dexterity': 12,
                'wisdom': 12},
                'levels': {'1': {'min_xp': 0,
                    'num_proficiencies': 1},
                    '10': {'min_xp': 500000},
                    '11': {'base_attack_bonus': 5,
                        'min_xp': 700000,
                        'num_proficiencies': 6},
                    '12': {'min_xp': 950000},
                    '13': {'base_attack_bonus': 6,
                        'min_xp': 1250000,
                        'num_proficiencies': 7},
                    '14': {'min_xp': 1750000},
                    '15': {'base_attack_bonus': 7,
                        'min_xp': 2250000,
                        'num_proficiencies': 8},
                    '16': {'min_xp': 2750000},
                    '17': {'base_attack_bonus': 8,
                        'min_xp': 3250000,
                        'num_proficiencies': 9},
                    '18': {'min_xp': 3750000},
                    '19': {'min_xp': 4250000,
                        'num_proficiencies': 10},
                    '2': {'min_xp': 2250},
                    '20': {'min_xp': 4750000},
                    '3': {'base_attack_bonus': 1,
                        'min_xp': 4750,
                        'num_proficiencies': 2},
                    '4': {'min_xp': 10000},
                    '5': {'base_attack_bonus': 2,
                        'min_xp': 22500,
                        'num_proficiencies': 3},
                    '6': {'min_xp': 47500},
                    '7': {'base_attack_bonus': 3,
                        'min_xp': 98000,
                        'num_proficiencies': 4},
                    '8': {'min_xp': 200000},
                    '9': {'base_attack_bonus': 4,
                        'min_xp': 350000,
                        'num_proficiencies': 5}},
                    'non_proficiency': '-3'},
        'paladin': {'hit_die' : 'd10',
            'ability minimums': {
                'strength': 9,
                'constitution': 9,
                'wisdom': 9,
                'charisma': 12},
                'levels': {'1': {'base_attack_bonus': 1,
                    'min_xp': 0,
                    'num_proficiencies': 3},
                    '10': {'base_attack_bonus': 10,
                        'min_xp': 700000,
                        'num_proficiencies': 6},
                    '11': {'base_attack_bonus': 11,
                        'min_xp': 1050000},
                    '12': {'base_attack_bonus': 12,
                        'min_xp': 1400000},
                    '13': {'base_attack_bonus': 13,
                        'min_xp': 1750000,
                        'num_proficiencies': 7},
                    '14': {'base_attack_bonus': 14,
                        'min_xp': 2100000},
                    '15': {'base_attack_bonus': 15,
                        'min_xp': 2450000},
                    '16': {'base_attack_bonus': 16,
                        'min_xp': 2800000,
                        'num_proficiencies': 8},
                    '17': {'min_xp': 3150000},
                    '18': {'min_xp': 3500000},
                    '19': {'min_xp': 3850000,
                        'num_proficiencies': 9},
                    '2': {'base_attack_bonus': 2,
                        'min_xp': 2750},
                    '20': {'min_xp': 4200000},
                    '3': {'base_attack_bonus': 3,
                        'min_xp': 5500},
                    '4': {'base_attack_bonus': 4,
                        'min_xp': 12000,
                        'num_proficiencies': 4},
                    '5': {'base_attack_bonus': 5,
                        'min_xp': 24000},
                    '6': {'base_attack_bonus': 6,
                        'min_xp': 45000},
                    '7': {'base_attack_bonus': 7,
                        'min_xp': 95000,
                        'num_proficiencies': 5},
                    '8': {'base_attack_bonus': 8,
                        'min_xp': 175000},
                    '9': {'base_attack_bonus': 9,
                        'min_xp': 350000}},
                    'non_proficiency': '-2'},
        'ranger': {'hit_die': 'd10',
            'ability minimums': {
                'strength': 12,
                'constitution': 9,
                'wisdom': 9,
                'intelligence': 9},
                'levels': {'1': {'base_attack_bonus': 1,
                    'min_xp': 0,
                    'num_proficiencies': 3},
                    '10': {'base_attack_bonus': 10,
                        'min_xp': 325000,
                        'num_proficiencies': 6},
                    '11': {'base_attack_bonus': 11,
                        'min_xp': 575000},
                    '12': {'base_attack_bonus': 12,
                        'min_xp': 875000},
                    '13': {'base_attack_bonus': 13,
                        'min_xp': 1175000,
                        'num_proficiencies': 7},
                    '14': {'base_attack_bonus': 14,
                        'min_xp': 1475000},
                    '15': {'base_attack_bonus': 15,
                        'min_xp': 1775000},
                    '16': {'base_attack_bonus': 16,
                        'min_xp': 2075000,
                        'num_proficiencies': 8},
                    '17': {'min_xp': 2375000},
                    '18': {'min_xp': 2675000},
                    '19': {'min_xp': 2975000,
                        'num_proficiencies': 9},
                    '2': {'base_attack_bonus': 2,
                        'min_xp': 2250},
                    '20': {'min_xp': 3275000},
                    '3': {'base_attack_bonus': 3,
                        'min_xp': 4500},
                    '4': {'base_attack_bonus': 4,
                        'min_xp': 10000,
                        'num_proficiencies': 4},
                    '5': {'base_attack_bonus': 5,
                        'min_xp': 20000},
                    '6': {'base_attack_bonus': 6,
                        'min_xp': 40000},
                    '7': {'base_attack_bonus': 7,
                        'min_xp': 90000,
                        'num_proficiencies': 5},
                    '8': {'base_attack_bonus': 8,
                        'min_xp': 150000},
                    '9': {'base_attack_bonus': 9,
                        'min_xp': 225000}},
                    'non_proficiency': '-2'},
        'thief': {'hit_die' : 'd6',
            'ability minimums': {
                'dexterity': 9},
                'levels': {'1': {'min_xp': 0,
                    'num_proficiencies': 2},
                    '10': {'min_xp': 160000},
                    '11': {'base_attack_bonus': 5,
                        'min_xp': 220000},
                    '12': {'min_xp': 440000},
                    '13': {'base_attack_bonus': 6,
                        'min_xp': 660000,
                        'num_proficiencies': 5},
                    '14': {'min_xp': 880000},
                    '15': {'base_attack_bonus': 7,
                        'min_xp': 1100000},
                    '16': {'min_xp': 1320000},
                    '17': {'base_attack_bonus': 8,
                        'min_xp': 1540000,
                        'num_proficiencies': 6},
                    '18': {'min_xp': 1760000},
                    '19': {'min_xp': 1980000},
                    '2': {'min_xp': 1250},
                    '20': {'min_xp': 2200000},
                    '3': {'base_attack_bonus': 1,
                        'min_xp': 2500},
                    '4': {'min_xp': 5000},
                    '5': {'base_attack_bonus': 2,
                        'min_xp': 10000,
                        'num_proficiencies': 3},
                    '6': {'min_xp': 20000},
                    '7': {'base_attack_bonus': 3,
                        'min_xp': 42500},
                    '8': {'min_xp': 70000},
                    '9': {'base_attack_bonus': 4,
                        'min_xp': 110000,
                        'num_proficiencies': 4}},
                    'non_proficiency': '-3',
                    'weapon_choices': ['bolas', 'club', 'dagger', 'quarterstaff', 'sling', 'bow', 'shortsword'],
                    'ability_minimums': {'dexterity': '9'},
                    'bonus_xp_minimums': {'dexterity': '16'},
                    'armor_choices': {'padded', 'leather', 'studded'},
                    'shields': 'False'},
        }

#        "bard": {'hit_die': 'd6',
#                'weapon_choices': []}
#}
