from decimal import getcontext, Decimal
from collections import namedtuple
from pint import UnitRegistry

# "If you use Pint in multiple modules ... avoid creating multiple instances of the unit registry ... by instantiating the registry in a single place."
u = UnitRegistry(system="US")
u.load_definitions("units.txt")
Q = u.Quantity

# "[If] pickling and unpickling Quantities, [define] the registry as the application registry"
# set_application_registry(u)

getcontext().prec = 6

categories = {
    "aromatics": {
        "production": 32_585_143 * u.oz,
        "members": {
            "aloe",
            "camphor",
            "frankincense",
            "mistletoe",
            "myrrh",
            "wood, sandalwood",
            "wood, teak",
        },
    },
    "paper": {
        "production": 42_824_320 * u.oz,
        "members": {
            "paper",
            "papyrus",
        },
    },
    "paper goods": {
        "production": 13_792_768 * u.oz,
        "members": {
            "bookbinding",
            "fans",
            "parasols",
            "manuscript illumination",
            "paper lanterns",
            "papier-mache",
            "playing cards",
        },
    },
    "mastics": {
        "production": 48_384_000 * u.oz,
        "members": {
            "asafoetida",
            "resin",
            "gum arabic",
            "gum benzoin",
            "gum mastic",
            "gum tragacanth",
            "gum",
        },
    },
    "oilseed": {
        "references": 29,
        "production": 6_573_916_160 * u.oz,
        "members": {
            "cottonseed",
            "linseed",
            "mustard seed",
            "poppyseed",
            "safflower seed",
            "sesame seed",
            "sunflower seed",
            "tamarind seed",
        },
    },
    "confectionery": {
        "references": 21,
        "production": 620_827_648 * u.oz,
        "members": {
            "chocolate",
            "edible birds' nests",
            "treacle",
            "treacle",
            "maraschino cherries",
        },
    },
    "fowl": {
        "references": 59,
        "production": 140_660_000 * u.head,
        "members": {
            "ducks",
            "chickens",
            "geese",
            "turkeys",
            "cormorants",
        },
    },
    "perfume": {
        "references": 41,
        "production": 3_204_813 * u.oz,
        "members": {
            "attar of roses",
            "civet",
            "musk",
        },
    },
    "pulses": {
        "references": 11,
        "production": 94_639_360_000 * u.oz,
        "members": {
            "alfalfa",
            "beans",
            "chickpeas",
            "clover",
            "hay",
            "lentils",
            "peas",
            "dried peas",
            "soybeans",
            "vetch",
        },
    },
    "cereals": {
        "references": 619,
        "production": 91_834_982_400 * u.oz,
        "members": {
            "barley",
            "gram",
            "maize",
            "millet",
            "oats",
            "rice",
            "rye",
            "sorghum",
            "teff and tucusso",
            "wheat",
        },
    },
    "wax": {
        "references": 0,
        "production": 12_837_888 * u.oz,
        "members": {
            "ozocerite",
            "candles and wax",
            "vegetable tallow",
        },
    },
    "fruits": {
        "references": 518,
        "production": 1_354_602_965 * u.oz,
        "members": {
            "apples",
            "apricots",
            "avocados",
            "bananas",
            "blackberries",
            "breadfruit",
            "cantaloupes",
            "cherries",
            "citrons",
            "clementines",
            "cob apples",
            "coconuts",
            "currants",
            "dates",
            "figs",
            "gooseberries",
            "grapefruit",
            "grapes",
            "guavas",
            "hushhash",
            "juniper berries",
            "lemons",
            "limes",
            "longan",
            "lichees",
            "loquats",
            "mandarin oranges",
            "mangoes",
            "melons",
            "muskmelons",
            "nectarines",
            "olives",
            "oranges",
            "papayas",
            "peaches",
            "pears",
            "persimmons",
            "pineapples",
            "plantains",
            "plums",
            "pomegranates",
            "prickly pears",
            "prunes",
            "pumpkins",
            "raisins",
            "raspberries",
            "strawberries",
            "tangerines",
            "watermelons",
            "whortleberries",
        },
    },
    "vegetables": {
        "references": 375,
        "production": 2_456_882_176 * u.oz,
        "members": {
            "asparagus",
            "cabbages",
            "cauliflower",
            "cucumbers",
            "eggplants",
            "garlic",
            "lily roots",
            "mushrooms",
            "onions",
            "peppers",
            "pimentos",
            "radishes",
            "rhubarb",
            "tomatoes",
            "turnips",
        },
    },
    "tubers": {
        "references": 8,
        "production": 2_906_760_192 * u.oz,
        "members": {
            "arrowroot",
            "potatoes",
            "sugarbeets",
            "sweet potatoes",
            "tapioca",
            "taro root",
            "yams",
            "groundnuts",
        },
    },
    "treenuts": {
        "references": 11,
        "production": 19_654_656 * u.oz,
        "members": {
            "almonds",
            "betel nuts",
            "carobs",
            "cashews",
            "chestnuts",
            "hazelnuts",
            "kola nuts",
            "palm nuts",
            "pistachios",
            "shea nuts",
            "tung nuts",
            "walnuts",
        },
    },
    "fish": {
        "references": 659,
        "production": 486_045_594 * u.oz,
        "members": {
            "anchovies",
            "barbel",
            "bonito",
            "bream",
            "carp",
            "catfish",
            "cod",
            "crabs",
            "crayfish",
            "cuttlefish",
            "eels",
            "flatfish",
            "flounder",
            "freshwater fish",
            "gudgeon",
            "haddock",
            "hake",
            "halibut",
            "herring",
            "lamprey",
            "ling",
            "lobsters",
            "mackerel",
            "mullet",
            "mussels",
            "navagu",
            "oysters",
            "perch",
            "pike",
            "pilchard",
            "roach",
            "salmon",
            "sardines",
            "sea slugs",
            "shark",
            "sponges",
            "sturgeon",
            "tilapia",
            "trout",
            "tuna",
            "turtles",
            "vogla",
            "whitefish",
        },
    },
    "building stones": {
        "members": {
            "alabaster",
            "basalt",
            "brownstone",
            "dolomite",
            "granite",
            "limestone",
            "marble, green",
            "marble, black",
            "marble, brown",
            "marble, crimson",
            "marble, gray",
            "marble, pink",
            "marble, white",
            "marble, yellow",
            "freestone",
            "porphyry",
            "sandstone",
            "red sandstone",
            "slate",
            "syenite",
            "trachyte",
            "tufa",
            "tuff",
        },
    },
    "timber": {
        "references": 539,
        "production": 114_793_944_640 * u.oz,
        "members": {
            "wood, African oak",
            "wood, aspen",
            "wood, bamboo",
            "wood, beech",
            "wood, birch",
            "wood, boxwood",
            "wood, carobwood",
            "wood, cedar",
            "wood, chestnut",
            "wood, cork",
            "wood, cypress",
            "wood, eucalyptus",
            "wood, fir",
            "wood, hornbeam",
            "wood, iroko",
            "wood, ironwood",
            "wood, jelutong",
            "wood, larch",
            "wood, laurel",
            "wood, mahogany",
            "wood, mangrove",
            "wood, oak",
            "wood, pine",
            "wood, redwood",
            "wood, rosewood",
            "wood, sandalwood",
            "wood, spruce",
            "wood, teak",
        },
    },
    "spices": None,
    "horses": None,
    "smithing": None,
}

# https://tao-dnd.blogspot.com/2008/07/commodities-list-part-i.html
# https://tao-dnd.blogspot.com/2008/07/commodities-list-part-ii.html

# dyestuffs
# carbon black, catechu, henna, indigo, madder, murex, ocher


# TODO sanity checks
# millet (grain) vs mullet (fish)
# cloves vs clover
# coral vs copal vs opal
# coral vs copal
# chestnut (wood) vs chestnuts (food)
# euphorbia (plant) vs euphoria (word)
# lac vs lace
# pepper (black) vs peppers (other) vs pimentos vs red pepper
# pears vs peas vs pearl v peat
# pots vs posts
# rhodonite vs rhodolite
# opal vs common opal vs fire opal vs precious opal vs water opal
# salon (hair dressing?) vs salmon


world_references = {
    "Esparto grass": {"references": 10},
    "Grand Chartreuse": {"references": 1},
    "Moroccan leathercraft": {"references": 4},
    "Perigord truffles": {"references": 1},
    "acid": {"references": 0, "production": 3_957_453 * u.oz},
    "acid, boric": {"references": 1},
    "adamantite": {"references": 6, "production": 297_760 * u.oz},
    "agate": {"references": 11},
    "alabaster": {"references": 8, "production": 1_092_766_558 * u.oz},
    "alchemy": {"references": 321},
    "alexandrite": {"references": 12},
    "alfalfa": {"references": 14},
    "alloys": {"references": 119},
    "almandine": {"references": 7},
    "almonds": {"references": 35},
    "aloe": {"references": 4},
    "alum": {"references": 6, "production": 1_478_185 * u.oz},
    "amber jewelry": {"references": 2},
    "amber": {"references": 24},
    "amethyst": {"references": 14},
    "anchovies": {"references": 6, "category": "fish"},
    "angora": {"references": 1},
    "anise": {"references": 3, "production": 196_332 * u.oz},
    "antimony": {"references": 43, "production": 3_359_461 * u.oz},
    "antimonysmelting": {"references": 2, "production": 180_736 * u.oz},
    "apples": {"references": 78},
    "apricots": {"references": 31},
    "aquamarine": {"references": 19},
    "arak": {"references": 1},
    "arbutus": {"references": 1},
    "armor": {"references": 45},
    "arrack": {"references": 2},
    "arrowroot": {"references": 3},
    "arsenic": {"references": 11, "production": 236_480 * u.oz},
    "artichokes": {"references": 1},
    "artistic glassware": {"references": 0, "production": 3_607_423 * u.oz},
    "artworks": {"references": 54},
    "asafoetida": {"references": 6},
    "asparagus": {"references": 5},
    "attar of roses": {"references": 8},
    "avocados": {"references": 3},
    "azulejos": {"references": 1},
    "azurite": {"references": 5},
    "bacon": {"references": 1},
    "bananas": {"references": 47},
    "banking": {"references": 37},
    "barbel": {"references": 1},
    "barges": {"references": 2},
    "barley": {"references": 212},
    "barrels": {"references": 15},
    "basalt": {"references": 2, "production": 222_700_425 * u.oz},
    "baskets": {"references": 12},
    "beads": {"references": 2},
    "beans": {"references": 68},
    "beans, Calabar": {"references": 1},
    "beans, castor": {"references": 27},
    "bear paws": {"references": 1, "production": 224_256 * u.oz},
    "bear skins": {"references": 8},
    "beaujolais": {"references": 3},
    "beef": {"references": 13},
    "bells": {"references": 7},
    # "berries": {"references": 2},
    "beryl": {"references": 4},
    "betel nuts": {"references": 19},
    "birdcages": {"references": 1},
    "bismuth": {"references": 4, "production": 312_508 * u.oz},
    "bitter salt": {"references": 14, "production": 75_768_877 * u.oz},
    "black coral": {"references": 5},
    "black powder": {"references": 5, "production": 254_061 * u.lb},
    "blackberries": {"references": 1},
    "blackcurrant liqueur": {"references": 1},
    "blankets": {"references": 11},
    "bloodstone": {"references": 5},
    "boatbuilding": {"references": 31},
    "bobbins": {"references": 1},
    "bonecarving": {"references": 2},
    "bonito": {"references": 4},
    "bookbinding": {"references": 101},
    "boots and shoes": {"references": 105},
    "borax": {"references": 8},
    "bottles": {"references": 3},
    "boxes": {"references": 2},
    "bracelets": {"references": 1},
    "brandy, Armagnac": {"references": 2},
    "brandy, apple": {"references": 2},
    "brandy, fruit": {"references": 1},
    "brandy, plum": {"references": 2},
    "brandywine": {"references": 23},
    "brass": {"references": 17},
    "brasswares": {"references": 17},
    "bread": {"references": 25},
    "bread, black": {"references": 2},
    "breadfruit": {"references": 1},
    "bream": {"references": 2, "category": "fish"},
    "brewing": {"references": 198, "production": 3_972_035_901 * u.floz},
    "bricks": {"references": 98, "production": 4_056_185_600 * u.oz},
    "bristles": {"references": 19, "production": 35_881_488 * u.oz},
    "brocade": {"references": 6},
    "bromine": {"references": 1},
    "bronze": {"references": 18},
    "brooms": {"references": 1},
    "brownstone": {"references": 1, "production": 203_389_393 * u.oz},
    "brushes": {"references": 9},
    "buckets": {"references": 1},
    "buckles": {"references": 1},
    "buffalo": {"references": 16},
    "building stone": {"references": 74},
    "butter": {"references": 84, "production": 435_499_008 * u.oz},
    "butter, Dorset": {"references": 1},
    "buttons": {"references": 6},
    "cabbages": {"references": 9},
    "cabinetmaking": {"references": 5},
    "cacao": {"references": 48, "production": 20_142_080 * u.oz},
    "cairngorm": {"references": 2},
    "cakes": {"references": 5},
    "calico cloth": {"references": 5},
    "cambric": {"references": 2},
    "camelhair": {"references": 4},
    "camels": {"references": 76, "production": 373_900 * u.head},
    "cameos": {"references": 1},
    "camphor": {"references": 6},
    "canaries": {"references": 1},
    "candles and wax": {"references": 95},
    "cannon": {"references": 2},
    "cantaloupes": {"references": 1},
    "canvas": {"references": 9},
    "carbon black": {"references": 1},
    "cardamom": {"references": 7, "production": 2_508_800 * u.oz},
    "carnations": {"references": 3},
    "carnelian": {"references": 4},
    "carobs": {"references": 3},
    "carp": {"references": 3},
    "carpentry": {"references": 17},
    "carpets": {"references": 110, "production": 519_502 * u.sqyd},
    "carriages": {"references": 12},
    "carts": {"references": 72},
    "cashews": {"references": 4},
    "cassavas": {"references": 18},
    "cassia": {"references": 1},
    "castor oil": {"references": 4},
    "casuarina": {"references": 1},
    "cat's eye": {"references": 9},
    "catechu": {"references": 4},
    "catfish": {"references": 1, "category": "fish"},
    "cattle": {"references": 486, "production": 12_588_600 * u.head},
    "cauliflower": {"references": 1},
    "caviar": {"references": 10, "production": 28_672 * u.oz},
    "cellos": {"references": 3},
    "cement": {"references": 131, "production": 6_218_604_800 * u.oz},
    "ceramics": {"references": 57, "production": 162_713_528 * u.oz},
    "chain": {"references": 2},
    "chalcedony": {"references": 4},
    "chalk": {"references": 7, "production": 1_187_020_800 * u.oz},
    "chamomile": {"references": 1, "production": 5_017_600 * u.oz},
    "champagne": {"references": 9},
    "charcoal": {"references": 15},
    "cheese": {"references": 84, "production": 682_264_576 * u.oz},
    "cheese, Camembert": {"references": 1},
    "cheese, Edam": {"references": 3},
    "cheese, Gouda": {"references": 1},
    "cheese, Gruyere": {"references": 2},
    "cheese, Limberger": {"references": 1},
    "cheese, Parmagiano": {"references": 1},
    "cheese, Stilton": {"references": 4},
    "cheese, cheddar": {"references": 1},
    "cheese, ewes' milk": {"references": 1},
    "cheese, gorgonzola": {"references": 2},
    "cheese, pont l'eveque": {"references": 1},
    "cheese, red Leicester": {"references": 1},
    "cherries": {"references": 19},
    "chestnuts": {"references": 35},
    "chickens": {"references": 18},
    "chickpeas": {"references": 5},
    "chicory": {"references": 10},
    "china": {"references": 15},
    "chocolate": {"references": 41},
    "chromium": {"references": 43, "production": 135_618_560 * u.oz},
    "chrysoprase": {"references": 8},
    "cider": {"references": 24, "production": 8_960_000 * u.floz},
    "cinchona": {"references": 7},
    "cinnamon leaf oil": {"references": 1},
    "cinnamon": {"references": 9, "production": 8_673_280 * u.oz},
    "citrine": {"references": 13},
    "citronella oil": {"references": 4},
    "citrons": {"references": 5},
    # "citrus": {"references": 71},
    "civet": {"references": 1},
    "clementines": {"references": 1},
    "clockmaking": {"references": 47},
    "cloisonne": {"references": 1},
    "cloth": {"references": 599},
    "clothing": {"references": 93},
    "clover": {"references": 6},
    "cloverseed": {"references": 2},
    "cloves": {"references": 7, "production": 8_458_240 * u.oz},
    "coal": {"references": 875, "production": 23_935_364_096 * u.oz},
    "cob apples": {"references": 1},
    "cobalt": {"references": 14, "production": 231_813 * u.oz},
    "cobaltsmelting": {"references": 1},
    "cochineal": {"references": 2},
    "coconut oil": {"references": 1},
    "coconuts": {"references": 57},
    "cod liver oil": {"references": 2},
    "cod": {"references": 20, "category": "fish"},
    "coffee": {"references": 78, "production": 3_239_040 * u.lb},
    "coffins": {"references": 1},
    "cognac": {"references": 4},
    "coir": {"references": 7},
    "colza": {"references": 3},
    "combs": {"references": 1},
    "common opal": {"references": 5},
    "copal": {"references": 7},
    "copper": {"references": 230, "production": 187_966_464 * u.oz},
    "coppersmelting": {"references": 47, "production": 36_544_466 * u.oz},
    "coppersmithing": {"references": 26, "production": 24_107_504 * u.oz},
    "copra": {"references": 25},
    "coral": {"references": 13},
    "coriander": {"references": 1, "production": 56_125 * u.oz},
    "cormorants": {"references": 1},
    "corsets": {"references": 1},
    "corundum": {"references": 2},
    "cosmetics": {"references": 2, "production": 269_431 * u.oz},
    "cotton cloth": {"references": 227, "production": 339_151_777 * u.sqyd},
    "cotton goods": {"references": 63, "production": 70_835_498 * u.sqyd},
    "cotton": {"references": 338, "production": 4_774_748_160 * u.oz},
    "cottonseed": {"references": 4},
    "crabs": {"references": 5, "category": "fish"},
    "crayfish": {"references": 1, "category": "fish"},
    "cream": {"references": 17},
    "crockery": {"references": 2},
    "cryptomeria": {"references": 1},
    "crystal": {"references": 5},
    "cucumbers": {"references": 5},
    "cumin": {"references": 2, "production": 9_989_038 * u.oz},
    "currants": {"references": 13},
    "curtains": {"references": 1},
    "cuttlefish": {"references": 2, "category": "fish"},
    "daffodils": {"references": 3},
    "dairying": {"references": 140},
    "dalbergia": {"references": 1},
    "damascene": {"references": 1},
    "damask": {"references": 5},
    "darekh": {"references": 1},
    "dates": {"references": 69},
    "dhows": {"references": 3},
    "diamond": {"references": 65, "production": 3279 * u.oz},
    "diamondcutting": {"references": 5},
    "dim sum": {"references": 2},
    "distilling": {"references": 142, "production": 272_108_021 * u.oz},
    # originally 10_127 * u.head dogs
    "dogs": {"references": 4, "production": 20_500 * u.head},
    "dolls": {"references": 2},
    "dolomite": {"references": 2, "production": 378_216_586 * u.oz},
    "donkeys": {"references": 41, "production": 446_900 * u.head},
    "doors": {"references": 1},
    "drapery": {"references": 2},
    "dresses": {"references": 1},
    "dried fish": {"references": 117, "production": 339_813_736 * u.oz},
    "dried fruit": {"references": 51, "production": 32_606_945 * u.oz},
    "dried meat": {"references": 9, "production": 177_049_600 * u.oz},
    "dried peas": {"references": 1},
    "drugget goods": {"references": 1},
    "ducks": {"references": 7},
    "dyestuff": {"references": 71, "production": 11_495_703 * u.oz},
    "eau de Cologne": {"references": 1},
    "ebony": {"references": 10},
    "edible birds' nests": {"references": 3},
    "eels": {"references": 3, "category": "fish"},
    "eggplants": {"references": 1},
    "elaeocarpus": {"references": 1},
    "elephants": {"references": 10, "production": 50_637 * u.head},
    "elixir de Spa": {"references": 1},
    "embroidery": {"references": 46, "production": 788_234 * u.sqin},
    "emerald": {"references": 25},
    "emery": {"references": 5, "production": 89_035_630 * u.oz},
    "enamelware": {"references": 21},
    "engraving": {"references": 5},
    "equisetifolia": {"references": 1},
    "ermine": {"references": 3},
    "espadrilles": {"references": 1},
    "euphorbia": {"references": 1},
    "faience": {"references": 11},
    "fans": {"references": 3},
    "felt boots": {"references": 1},
    "felt caps": {"references": 8},
    "felt": {"references": 15},
    "fighting cocks": {"references": 1},
    "figs": {"references": 59},
    "figurines": {"references": 1},
    "files": {"references": 1},
    "fire opal": {"references": 8},
    "firecrackers": {"references": 8},
    "fish fins": {"references": 1},
    "fish hooks": {"references": 2},
    "fish meal": {"references": 1},
    "flags": {"references": 1},
    "flannel": {"references": 4},
    "flatfish": {"references": 1, "category": "fish"},
    "flatware": {"references": 1},
    "flax": {"references": 101, "production": 498_175_000 * u.oz},
    "flint": {"references": 12, "production": 567_417_633 * u.oz},
    "flounder": {"references": 1, "category": "fish"},
    "flour": {"references": 232, "production": 12_384_870_400 * u.oz},
    "flowers": {"references": 18},
    "fodder": {"references": 54},
    "foie gras": {"references": 3},
    "foodstuffs": {"references": 223},
    "fox furs": {"references": 6},
    "frankincense": {"references": 3},
    "freestone": {"references": 2, "production": 196_715_129 * u.oz},
    "freshwater fish": {"references": 52, "category": "fish"},
    "friezes": {"references": 2},
    "fur clothing": {"references": 2},
    "furnishings": {"references": 160},
    "furniture": {"references": 151},
    "furs": {"references": 77},
    "garlic": {"references": 2},
    "garnet": {"references": 7},
    "geese": {"references": 4},
    "gemcarving": {"references": 2},
    "gemcutting": {"references": 32},
    "ghee": {"references": 5},
    "gin": {"references": 4},
    "ginger": {"references": 7, "production": 55_603_395 * u.oz},
    "gingerbread": {"references": 1},
    "ginseng": {"references": 7, "production": 367_862 * u.oz},
    "glassware": {"references": 152, "production": 29_090_818 * u.oz},
    "glazed fruit": {"references": 1},
    "gloves": {"references": 35},
    "glue": {"references": 2},
    "gnomish beer": {"references": 1},  # originally pilsener beer
    "goat skins": {"references": 7},
    "goats": {"references": 129, "production": 6_294_340 * u.head},
    "gold filigree": {"references": 11},
    "gold inlay": {"references": 1},
    "gold": {"references": 237, "production": 311_529 * u.oz},
    "goldsmithing": {"references": 21, "production": 38_195 * u.oz},
    "gooseberries": {"references": 2},
    "goshenite": {"references": 1},
    "gowns": {"references": 2},
    "gram": {"references": 23},
    "granite": {"references": 49},
    "grapefruit": {"references": 6},
    "grapes": {
        "references": 351,
        "production": 321_922_048 * u.oz,
    },
    "griffs": {"references": 40, "production": 12_659 * u.head},
    "greenstone": {"references": 5},
    "grindstones": {"references": 4},
    "grossular": {"references": 8},
    # these plants produce both beans and tubers ... and they're called nuts! how confusing.
    "groundnuts": {"references": 89, "production": 1_104_588_800 * u.oz},
    "guano": {"references": 2, "production": 74_547_200 * u.oz},
    "guavas": {"references": 3},
    "gudgeon": {"references": 1},
    "gum arabic": {"references": 11},
    "gum benzoin": {"references": 1},
    "gum mastic": {"references": 4},
    "gum tragacanth": {"references": 2},
    "gum": {"references": 10},
    "gutta-percha": {"references": 1},
    "haddock": {"references": 4, "category": "fish"},
    "hake": {"references": 1, "category": "fish"},
    "halibut": {"references": 1},
    "handkerchiefs": {"references": 1},
    "harari": {"references": 1},
    "harpsichords": {"references": 3},
    "hats": {"references": 29},
    "hawk's eye": {"references": 1},
    "hay": {"references": 50},
    "hazelnuts": {"references": 3},
    "healing earth": {"references": 1},
    "heliodor": {"references": 4},
    "hematite": {"references": 10},
    "hemp goods": {"references": 18},
    # moved production from hemp goods to hemp
    "hemp": {"references": 95, "production": 57_008_085 * u.oz},
    "henna": {"references": 3},
    "herring": {"references": 46, "category": "fish"},
    "hessonite": {"references": 1},
    "hides": {"references": 349, "production": 251_023_360 * u.oz},
    "honey": {"references": 43, "production": 51_173_504 * u.oz},
    "hookahs": {"references": 21},  # originally waterpipe
    "hops": {"references": 23, "production": 6_104_412 * u.oz},
    "horn combs": {"references": 1},
    "horn": {"references": 2},
    "horn, antelope": {"references": 1},
    "horn, deer and elk": {"references": 2},
    "horncarving": {"references": 3},
    "horses": {"references": 185, "production": 546_880 * u.head},
    "horses, Brittany": {"references": 1},
    # "horses, Percheron": {"references": 5},
    # rolling Percherons into draft horses since I'm not running Earth
    "horses, draft": {"references": 6},
    "hosiery": {"references": 42},
    "hushhash": {"references": 5},  # sour orange
    "hyacinths": {"references": 1},
    "incense": {"references": 8},
    "indigo": {"references": 17},
    "ink": {"references": 12, "production": 7_456_870 * u.oz},
    "iodine": {"references": 1},
    "iron flowers": {"references": 1},
    "iron": {"references": 512, "production": 20_176_558_080 * u.oz},
    "ironmongery": {"references": 74, "production": 991_353_858 * u.oz},
    "ivory": {"references": 23, "production": 830_742 * u.oz},
    "ivorycarving": {"references": 10},
    "jade": {"references": 43},
    "jadecarving": {"references": 5},
    "jasper": {"references": 8},
    "jet": {"references": 4},
    "jeweled daggers": {"references": 1},
    "jewelry": {"references": 29},
    "juniper berries": {"references": 1},
    "jute": {"references": 32},
    "kaffir": {"references": 1},
    "kanku": {"references": 1},
    "kaolin": {"references": 43, "production": 1_082_152_960 * u.oz},
    "kapok": {"references": 4},
    "karakul": {"references": 5},
    "kenaf": {"references": 2},
    "kendyr": {"references": 1},
    "kid gloves": {"references": 1},
    "kid leather": {"references": 1},
    "kirschwasser": {"references": 4},
    "knives": {"references": 35},
    "kokura-ori": {"references": 1},
    "kola nuts": {"references": 10},
    "kumiss": {"references": 2},
    "kutani": {"references": 1},
    "lac": {"references": 4},  # as in shellac
    "lace": {"references": 78},
    "lace, Guipure": {"references": 1},
    "lacquerware": {"references": 24},
    "lamb": {"references": 1},
    "lamp oil": {"references": 84, "production": 30_638_272 * u.lb},
    "lamprey": {"references": 2, "category": "fish"},
    "lamps": {"references": 70},
    "lapidary": {"references": 6},
    "lapis lazuli": {"references": 10},
    "lard": {"references": 2},
    "lavender": {"references": 1},
    "lead": {"references": 214, "production": 109_691_904 * u.oz},
    "leadsmelting": {"references": 16, "production": 9_627_338 * u.oz},
    "leadsmithing": {"references": 4, "production": 1_553_947 * u.oz},
    "leathercraft": {"references": 165},
    "lemons": {"references": 23},
    "lenses": {"references": 21},
    "lentils": {"references": 11},
    "leopard skins": {"references": 4},
    "leopards": {"references": 1, "production": 5064 * u.head},
    "lichees": {"references": 6},
    "licorice": {"references": 9, "production": 2_150_400 * u.oz},
    "lilies": {"references": 3},
    "lily roots": {"references": 1},
    "limes": {"references": 5},
    "limestone": {"references": 79, "production": 10_712_144_744 * u.oz},
    "linen cloth": {"references": 112, "production": 5_945_558 * u.sqyd},
    "linen goods": {"references": 24, "production": 771_181 * u.sqyd},
    "ling": {"references": 1, "category": "fish"},
    "lingerie": {"references": 5},
    "linseed oil": {"references": 3},
    "linseed": {"references": 22},
    "liqueur": {"references": 7},
    "lithographic stone": {"references": 2, "production": 232_312_699 * u.oz},
    "livestock": {"references": 484},
    "lobsters": {"references": 7, "category": "fish"},
    "locks": {"references": 4},
    "looms": {"references": 12},
    "loquats": {"references": 2},
    "lotus": {"references": 2},
    "longan": {"references": 1},
    "lye": {"references": 2, "production": 10_054_464 * u.lb},
    "lynx furs": {"references": 1},
    "mackerel": {"references": 8, "category": "fish"},
    "madder": {"references": 4},
    "magnesite": {"references": 21, "production": 1_186_418_688 * u.oz},
    "maize": {"references": 275},
    "majolica": {"references": 7},
    "malachite": {"references": 6},
    "malt": {"references": 8, "production": 68_919_962 * u.oz},
    "mandarin oranges": {"references": 6},
    "manganese": {"references": 106, "production": 273_824_768 * u.oz},
    "mangoes": {"references": 7},
    "manuscript illumination": {"references": 4},
    "maraschino cherries": {"references": 3},
    "marble": {"references": 89},
    # green = Cipollina
    "marble, green": {"references": 3, "production": 38_779_006 * u.oz},
    "marble, black": {"references": 2, "production": 13_298_263 * u.oz},
    "marble, brown": {"references": 1, "production": 13_578_908 * u.oz},
    "marble, crimson": {"references": 3, "production": 28_025_553 * u.oz},
    "marble, gray": {"references": 1, "production": 728_018_165 * u.oz},
    "marble, pink": {"references": 1, "production": 1_867_100 * u.oz},
    "marble, white": {"references": 7, "production": 75_483_858 * u.oz},
    "marble, yellow": {"references": 1, "production": 13_578_908 * u.oz},
    "marigolds": {"references": 3},
    "markets": {"references": 3159},
    "masonry": {"references": 42, "production": 4_586_605_064 * u.oz},
    "mats": {"references": 12},
    "meat": {"references": 98},
    # originally medicinal agents
    "medicinal plants": {"references": 51, "production": 478_536 * u.oz},
    "meerschaum": {"references": 1, "production": 37_315_619 * u.oz},
    "melanite": {"references": 3},
    "melons": {"references": 39},
    "mercury": {"references": 38, "production": 307_292 * u.oz},
    "metalsmithing": {"references": 133},
    "milk of magnesia": {"references": 1},
    "milk": {"references": 17, "production": 26_200_400 * u.gallon},
    "millet": {"references": 165},
    "mineral water": {"references": 13, "production": 338_326 * u.floz},
    "minting": {"references": 5},
    "mirrors": {"references": 2},
    "mistletoe": {"references": 2},
    "mithril": {"references": 13, "production": 297_760 * u.oz},
    "mlombwa": {"references": 1},  # mlombwa is a plant/tree
    "mninga": {"references": 1},
    "mohair cloth": {"references": 7},
    "mohair": {"references": 1},
    "molybdenum": {"references": 16, "production": 1_250_032 * u.oz},
    "moonstone": {"references": 24},
    "morganite": {"references": 6},
    "mosaics": {"references": 1},
    "moss agate": {"references": 11},
    "mother of pearl inlay": {"references": 1},
    "mother of pearl": {"references": 4},
    "mules": {"references": 33, "production": 126_200 * u.head},
    "mullet": {"references": 1},
    "murex": {"references": 3},
    "muscatel": {"references": 4},
    "mushrooms": {"references": 7},
    "music scripting": {"references": 1},
    "musical instruments": {"references": 28},
    "musk": {"references": 4},
    "muskmelons": {"references": 1},
    "muslin goods": {"references": 2},
    "muslin": {"references": 9},
    "mussels": {"references": 3, "category": "fish"},
    "mustard seed": {"references": 1},
    # originally mustard and sauces
    "mustard": {"references": 4, "production": 64_365_645 * u.oz},
    "mutton": {"references": 9},
    "myrrh": {"references": 3},
    "nails": {"references": 3},
    "narcissi": {"references": 3},
    "navagu": {"references": 1},
    "necklaces": {"references": 1},
    "nectarines": {"references": 1},
    "needles": {"references": 8},
    "nets": {"references": 9},
    "nickel": {"references": 30, "production": 22_488_812 * u.oz},
    "nickelsmelting": {"references": 5, "production": 3_806_386 * u.oz},
    "niter": {"references": 2, "production": 470_938 * u.lb},
    "noodles": {"references": 5},
    "nutgall": {"references": 1},
    "nutmeg": {"references": 2, "production": 5_304_320 * u.oz},
    "oatmeal": {"references": 1},
    "oats": {"references": 158},
    "obsidian": {"references": 1, "production": 40_960_000 * u.oz},
    "ocher": {"references": 10},
    "olive oil": {"references": 109},
    "olives": {"references": 219},
    "onions": {"references": 7},
    "onyx": {"references": 4},
    "opal": {"references": 12},
    "opium": {"references": 26, "production": 300_489 * u.oz},
    "oranges": {"references": 69},
    "organs": {"references": 2},
    "ornaments": {"references": 6},
    "ostrich feathers": {"references": 4, "production": 44_848 * u.oz},
    "ostriches": {"references": 3},
    "otter furs": {"references": 1},
    "ovens": {"references": 19},
    "oysters": {"references": 25, "category": "fish"},
    "ozocerite": {"references": 3},
    "paint": {"references": 20},
    "palm nuts": {"references": 23},
    "palm oil": {"references": 35},
    "palms": {"references": 16},
    "pans": {"references": 2},
    "papayas": {"references": 3},
    "paper lanterns": {"references": 1},
    "paper products": {"references": 6, "production": 13_792_768 * u.oz},
    "paper": {"references": 255},
    "papier-mache": {"references": 1},
    "paprika": {"references": 2, "production": 25_017_969 * u.oz},
    "papyrus": {"references": 4},
    "parasols": {"references": 6},
    "parchment": {"references": 2},
    "parquet stone": {"references": 1},
    "patchouli": {"references": 1},
    "pate": {"references": 1},
    "peaches": {"references": 23},
    "peanut oil": {"references": 7},
    "pearl": {"references": 35},
    "pears": {"references": 27},
    "peas": {"references": 21},
    "peat": {"references": 33, "production": 1_435_105_289 * u.oz},
    "pepper, black": {"references": 20, "production": 24_657_920 * u.oz},
    "pepper, red": {"references": 1},
    "peppermint": {"references": 1},
    "peppers": {"references": 5},
    "perch": {"references": 2, "category": "fish"},
    "peridot": {"references": 10},
    "perilla seed": {"references": 1},
    "perry": {"references": 3, "production": 1_120_000 * u.floz},
    "persimmons": {"references": 2},
    "petrified wood": {"references": 4},
    "pewter": {"references": 1},
    "pewterware": {"references": 2},
    "phosphorus": {"references": 7, "production": 128_000 * u.oz},
    "piassava": {"references": 4},
    "pig iron": {"references": 403, "production": 8_850_520_591 * u.oz},
    "pike": {"references": 4, "category": "fish"},
    "pilchard": {"references": 3, "category": "fish"},
    "pimentos": {"references": 2},
    "pineapples": {"references": 16},
    "pistachios": {"references": 7},
    "pitch": {"references": 21, "production": 2_671_872 * u.lb},
    # TODO convert plant oil to floz
    "plant oil": {"references": 0, "production": 2_176_348_160 * u.oz},
    "plantains": {"references": 4},
    "plaster": {"references": 2},
    "platinum": {"references": 14, "production": 25_090 * u.oz},
    "playing cards": {"references": 1},
    "ploughs": {"references": 5},
    "plums": {"references": 22},
    "plush": {"references": 1},
    "podo": {"references": 1},
    "podocarpus": {"references": 1},
    "poison": {"references": 9, "production": 861_728 * u.lb},
    "pollan": {"references": 1},
    "pomegranates": {"references": 18},
    "pongee": {"references": 2},
    "ponies": {"references": 2},
    "ponies, Welsh": {"references": 1},
    "poppyseed": {"references": 6},
    "porcelain": {"references": 73, "production": 77_362_504 * u.oz},
    "pork": {"references": 1},
    "porphyry": {"references": 4, "production": 490_784_353 * u.oz},
    "port": {"references": 9},
    "posts": {"references": 3},
    "potatoes": {"references": 201},
    "pots": {"references": 1},
    "pottery": {"references": 142},
    "poultry and eggs": {"references": 16},
    "prase": {"references": 4},
    "prayer carpets": {"references": 1},
    "precision tools": {"references": 36},
    "presses": {"references": 10},
    "prickly pears": {"references": 1},
    "prunes": {"references": 5},
    "pumice": {"references": 2, "production": 35_614_252 * u.oz},
    "pumpkins": {"references": 1},
    "pumps": {"references": 4},
    "pyrope": {"references": 3},
    "qat": {"references": 1, "production": 11_557 * u.oz},
    "quality swords": {"references": 2},
    "quartz": {"references": 15},
    "quartz, blue": {"references": 6},
    "quartz, rose": {"references": 2},
    "quicklime": {"references": 16, "production": 5_368_832_000 * u.oz},
    "quinine": {"references": 1},
    "rabbits": {"references": 1, "production": 1_352_500 * u.head},
    "racehorses": {"references": 3},
    "radishes": {"references": 3},
    "raffia": {"references": 3},
    "raisins": {"references": 20},
    "ramie": {"references": 6},
    "rapeseed oil": {"references": 1},
    "rapeseed": {"references": 34},
    "raspberries": {"references": 2},
    "rattan": {"references": 4},
    "red sandstone": {"references": 3, "production": 271_616_994 * u.oz},
    "red stamp ink": {"references": 1},
    "refined sugar": {"references": 191},
    "reindeer": {"references": 191, "production": 121_529 * u.head},
    "resin": {"references": 12},
    "rhodochrosite": {"references": 3},
    "rhodolite": {"references": 5},
    "rhodonite": {"references": 8},
    "rhubarb": {"references": 2},
    "ribbon": {"references": 7},
    "rice": {"references": 444},
    "roach": {"references": 1},
    "robes": {"references": 1},
    "rope": {"references": 62},
    "rosaries": {"references": 4},
    "roses": {"references": 9},
    "rosin": {"references": 1},
    "rough fiber cloth": {"references": 26, "production": 2_754_662_400 * u.lb},
    "rough fibers": {"references": 5, "production": 22_111_332 * u.sqyd},
    "ruby": {"references": 32},
    "rum": {"references": 5},
    "rye": {"references": 108},
    "sable": {"references": 4},
    "sacks": {"references": 4},
    "saddles": {"references": 7},
    "safflower seed": {"references": 1},
    "saffron": {"references": 8, "production": 11_476 * u.oz},
    "sago": {"references": 1},
    "sailcloth": {"references": 10},
    "sake": {"references": 4},
    "sal ammoniac": {"references": 1, "production": 6_314_073 * u.oz},
    "sal": {"references": 1},
    "salmon": {"references": 30},
    # salon is apparently a kind of fish, but I can't find more info
    # "salon": {"references": 1},
    "salt": {"references": 230, "production": 771_592_192 * u.oz},
    "salted duck": {"references": 1},
    "samovars": {"references": 1},
    "sandals and slippers": {"references": 4},
    "sandstone": {"references": 19, "production": 1_795_379_121 * u.oz},
    "santonin": {"references": 1},
    "sapphire": {"references": 31},
    "saragoca": {"references": 1},
    "sardine oil": {"references": 1},
    "sardines": {"references": 33},
    "satin": {"references": 1},
    "satinwood": {"references": 1},
    "sauerkraut": {"references": 2},
    "sausage": {"references": 6},
    "saws": {"references": 3},
    "scissors": {"references": 2},
    "sculpture": {"references": 7},
    "sea ivory": {"references": 9, "production": 1_661_504 * u.oz},
    "sea slugs": {"references": 1},
    "seal skins": {"references": 13},
    "seaweed": {"references": 6},
    "seed oil": {"references": 16},
    "senna": {"references": 1},
    "serge": {"references": 1},
    "sesame seed oil": {"references": 1},
    "sesame seed": {"references": 46},
    "shad": {"references": 1},
    "shark fins": {"references": 1},
    "shark liver oil": {"references": 2},
    "shark": {"references": 1},
    "shawls": {"references": 10},
    "shea butter": {"references": 2},
    "shea nuts": {"references": 3},
    "sheep skins": {"references": 8},
    "sheep": {"references": 353, "production": 12_288_600 * u.head},
    "sheepskin coats": {"references": 1},
    "shellac": {"references": 1},
    "shellfish": {"references": 3},
    "sherry": {"references": 6},
    "sherry, Amontillado": {"references": 1},
    "ship rigging": {"references": 2},
    "shipbuilding": {"references": 233},
    "shrimp": {"references": 4},
    "siege engines": {"references": 8},
    "siliphium": {"references": 1},
    "silk cloth": {"references": 130, "production": 3_170_451 * u.sqyd},
    "silk goods": {"references": 37, "production": 839_741 * u.oz},
    "silk": {"references": 234, "production": 50_727_216 * u.oz},
    "silver filigree": {"references": 8},
    "silver inlay": {"references": 2},
    "silver": {"references": 102, "production": 2_302_362 * u.oz},
    "silversmithing": {"references": 36, "production": 736_756 * u.oz},
    "sisal": {"references": 12},
    "skins": {"references": 46},
    "slate": {"references": 49, "production": 2_342_860_800 * u.oz},
    "slaves": {"references": 51, "production": 810_190 * u.head},
    "smelting": {"references": 109},
    "smoked ham": {"references": 5},
    "smoking pipes": {"references": 2},
    "snake skins": {"references": 1},
    "snow leopard skins": {"references": 1},
    "snuff": {"references": 115, "production": 8_124_928 * u.oz},
    "soap": {"references": 124, "production": 273_056_205 * u.oz},
    "soda ash": {"references": 14, "production": 63_140_730 * u.oz},
    "sorghum": {"references": 76},
    "soybean oil": {"references": 10},
    "soybeans": {"references": 51},
    "spessartite": {"references": 7},
    "spices": {"references": 45, "production": 225_498_837 * u.oz},
    "spinel": {"references": 9},
    "sponges": {"references": 11},
    "squeezeboxes": {"references": 1},
    "stained glass": {"references": 6},
    "starch": {"references": 15},
    "stonecarving": {"references": 1},
    "straw goods": {"references": 8},
    "straw hats": {"references": 8},
    "strawberries": {"references": 7},
    "strega": {"references": 1},
    "sturgeon": {"references": 11},
    "sugar": {"references": 0, "production": 3_266_959_360 * u.oz},
    "sugarbeets": {"references": 136, "production": 1_720_268_800 * u.oz},
    "sugarcane": {"references": 143, "production": 2_866_988_800 * u.oz},
    "sugared almonds": {"references": 1},
    "sulfur": {"references": 62, "production": 66_368_512 * u.oz},
    "sunflower seed oil": {"references": 1},
    "sunflower seed": {"references": 17},
    "sweet potatoes": {"references": 26},
    "swine": {"references": 111, "production": 13_455_560 * u.head},
    "swords": {"references": 4},
    "syenite": {"references": 1, "production": 116_222_510 * u.oz},
    "tablecloths": {"references": 2},
    "talc": {"references": 5, "production": 422_400_000 * u.oz},
    "tamarind seed": {"references": 2},
    "tamarisk": {"references": 1},
    "tangerines": {"references": 7},
    "tapestries": {"references": 25},
    "tapioca": {"references": 6},
    "taro root": {"references": 1},
    "tartans": {"references": 1},
    "tea": {"references": 153, "production": 155_115_520 * u.oz},
    "teak oil": {"references": 1},
    "teff and tucusso": {"references": 2},
    "tents": {"references": 4},
    "terra cotta": {"references": 4},
    "thatch": {"references": 6},
    "tiger skins": {"references": 3},
    "tiger's eye": {"references": 5},
    "tilapia": {"references": 2},
    "tiles": {"references": 50},
    "tin": {"references": 87, "production": 8_951_327 * u.oz},
    "tinsmelting": {"references": 6, "production": 695_982 * u.oz},
    "tinsmithing": {"references": 14, "production": 456_709 * u.oz},
    "tobacco": {"references": 333, "production": 342_845_440 * u.oz},
    "tomatoes": {"references": 11},
    "tonic": {"references": 1},
    "tools": {"references": 378, "production": 817_026_800 * u.oz},
    "topaz": {"references": 18},
    "topazolite": {"references": 2},
    "tortoise shell carving": {"references": 1},
    "tortoise shell": {"references": 3, "production": 237_360 * u.oz},
    "tourmaline": {"references": 23},
    "toys": {"references": 19},
    "trachyte": {"references": 1, "production": 136_568_417 * u.oz},
    "treacle": {"references": 5},
    "trout": {"references": 6},
    "truffles": {"references": 4},
    "tufa": {"references": 1, "production": 188_684_597 * u.oz},
    "tuff": {"references": 1, "production": 80_664_348 * u.oz},
    "tulips": {"references": 5},
    "tulle": {"references": 3},
    "tuna": {"references": 21},
    "tung nuts": {"references": 1},
    "tung oil": {"references": 21},
    "tungsten": {"references": 41, "production": 2_670_864 * u.oz},
    "turkeys": {"references": 3},
    "turmeric": {"references": 2, "production": 57_344_000 * u.oz},
    "turnips": {"references": 26},
    "turquoise": {"references": 15},
    "turtles": {"references": 5},
    "tweed": {"references": 4},
    "tweed, Harris": {"references": 2},
    "twine": {"references": 1},
    "umber": {"references": 1},
    "uvarovite": {"references": 5},
    "vanadium": {"references": 3},
    "vanilla": {"references": 7},
    "vegetable oil": {"references": 27},
    "vegetable tallow": {"references": 1},
    "velour goods": {"references": 1},
    "velour": {"references": 1},
    "velvet goods": {"references": 1},
    "velvet": {"references": 9},
    "veneer": {"references": 3},
    "vermouth": {"references": 1},
    "vestments": {"references": 1},
    "vetch": {"references": 1},
    "vignettes": {"references": 1},
    "vinegar": {"references": 7},
    "violets": {"references": 2},
    "violins": {"references": 6},
    "vitriol": {"references": 10},
    "vogla": {"references": 1},
    "wagons": {"references": 190},
    "walnuts": {"references": 16},
    "ware, Barum": {"references": 1},
    "ware, Esparto": {"references": 1},
    "ware, Lowestoft": {"references": 1},
    "ware, Tunbridge": {"references": 1},
    "water opal": {"references": 1},
    "watermelons": {"references": 5},
    "watermills": {"references": 21},
    "weapons": {"references": 48},
    "whale oil": {"references": 28, "production": 8_078_336 * u.floz},
    "wheat": {"references": 567},
    "whiskey": {"references": 11},
    "whitefish": {"references": 3},
    "whortleberries": {"references": 3},
    "willow wands": {"references": 1},
    "windmills": {"references": 16},
    "windows": {"references": 2},
    "wine": {"references": 361, "production": 1_508_266_707 * u.floz},
    "wine, Baccia": {"references": 1},  # originally Badocsony
    "wine, Chablis": {"references": 3},
    "wine, Chabrieres": {"references": 1},
    "wine, Chianti": {"references": 2},
    "wine, La Rioja": {"references": 2},
    "wine, Madeira": {"references": 1},
    "wine, Malaga": {"references": 3},
    # Lutewood originally Malvoisie: pinot gris wine or skin-contact wine
    "wine, Lutewood": {"references": 1},
    "wine, Marsala": {"references": 3},
    # Sacramaran originally Malvasia: pinot gris wine or skin-contact wine
    "wine, Sacramaran": {"references": 1},
    "wine, Mees": {"references": 1},
    "wine, Montona": {"references": 1},
    "wine, Tokay": {"references": 1},
    "wine, Valtellina": {"references": 1},
    "wine, asti spumante": {"references": 2},
    "wine, black": {"references": 1},
    "wine, canary sack": {"references": 1},
    "wire": {"references": 9},
    "witherite": {"references": 2, "production": 2_751_078 * u.oz},
    "wolf furs": {"references": 2},
    "wood alcohol": {"references": 6, "production": 287_275 * u.pint},
    "wood oil": {"references": 2},
    "wood, African oak": {"references": 1},
    "wood, aspen": {"references": 1},
    "wood, bamboo": {"references": 8},
    "wood, beech": {"references": 7},
    "wood, birch": {"references": 2},
    "wood, boxwood": {"references": 2},
    "wood, carobwood": {"references": 1},
    "wood, cedar": {"references": 6},
    "wood, chestnut": {"references": 15},
    "wood, cork": {"references": 38},
    "wood, cypress": {"references": 2},
    "wood, eucalyptus": {"references": 1},
    "wood, fir": {"references": 7},
    "wood, hornbeam": {"references": 1},
    "wood, iroko": {"references": 1},
    "wood, ironwood": {"references": 4},
    "wood, jelutong": {"references": 1},
    "wood, larch": {"references": 2},
    "wood, laurel": {"references": 1},
    "wood, mahogany": {"references": 12},
    "wood, mangrove": {"references": 3},
    "wood, oak": {"references": 16},
    "wood, pine": {"references": 15},
    "wood, redwood": {"references": 1},
    "wood, rosewood": {"references": 2},
    "wood, sandalwood": {"references": 5},
    "wood, spruce": {"references": 3},
    "wood, teak": {"references": 24},
    "woodcarving": {"references": 15},
    "woodcraft": {"references": 124},
    "wooden shoes": {"references": 1},
    "wooden tools": {"references": 110},
    "wool": {"references": 147, "production": 33_323_136 * u.lb},
    "woolen cloth": {"references": 111, "production": 13_791_196 * u.sqyd},
    "woolen goods": {"references": 116, "production": 7_009_387 * u.sqyd},
    "worsted cloth": {"references": 5},
    "worsted goods": {"references": 4},
    "yak tails": {"references": 2},
    "yaks": {"references": 4},
    "yams": {"references": 23},
    "yeast": {"references": 5},
    "zinc": {"references": 129, "production": 231_232_512 * u.oz},
    "zincsmelting": {"references": 9, "production": 18_171_375 * u.oz},
    "zircon": {"references": 9},
    "zsolnay": {"references": 1},
}


def distribute_category(world_references, category, info):
    """Distribute production totals for a category of reference into the specific references within that category.

    For instance, we have a production total for generic fruit, but nothing for whortleberries, apples, etc., so we assign a portion of the fruit production total to those more-specific fruit references.

    If fruits['production'] == 1000 oz, total_refs == 100, m == 'apples', and world_references['apples']['references'] == 1, assign 1 / 100 * 1000 oz = 10 oz to world_references['apples']['production']"""
    total_refs = sum([world_references[m]["references"] for m in info["members"]])
    generic_refs = info.get("references", 0)
    # TODO better way to use generic_refs?
    # TODO once Cheapest or similar is better established, maybe _don't_ put category into world_references... although it IS useful as a generic. sort of an alternate way to represent 'cheapest'/whatever works
    if generic_refs:
        world_references[category] = {
            "references": generic_refs,
            "production": info["production"],
        }
    for m in info["members"]:
        if world_references[m].get("production"):
            # that member already has production specified, e.g. grapes in the fruit category
            continue
        else:
            r = world_references[m]["references"]
            fraction = r / total_refs
            world_references[m]["production"] = fraction * info["production"]


for category, info in categories.items():
    if info is None or "members" not in info or "production" not in info:
        # defensive programming for unfinished categories
        continue
    else:
        distribute_category(world_references, category, info)


for r, info in world_references.items():
    # decimalize reference counts and production totals
    info["references"] = Decimal(info["references"])
    if "production" in info:
        info["production"] = (
            Decimal(info["production"].magnitude) * info["production"].units
        )
    else:
        info["production"] = Decimal(0) * u.unit
    # set production per reference
    refs = info["references"]
    prod = info["production"]
    if refs == 0 or prod.magnitude == 0:
        # 'zero problem' - see towns.py
        continue
    else:
        info["production per reference"] = (prod.magnitude / refs) * prod.units


def main():
    # q = categories["fish"]["members"]
    # d = set(
    #    [k for k, info in world_references.items() if info.get("category") == "fish"]
    # )
    # print(q, len(q))
    # print(d, len(d))
    # print(d - q, len(d - q))
    # print(q - d, len(q - d))
    for w, info in world_references.items():
        refs = info["references"]
        ppr = info.get("production per reference")
        prod = info["production"]
        name = w.title()
        if ppr:
            print(f"{name}: {refs} refs at {ppr}")
        elif refs and not prod:
            print(f"{name}: {refs} refs")
        else:
            print(f"{name}: world production {prod}")


if __name__ == "__main__":
    main()
