name: test-gh-actions
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build and Test Code
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Code
        uses: actions/checkout@v3
      - name: Set Up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest poetry
          poetry install
      - name: Test with Pytest
        run: |
          cd dnd
          dotests.sh
  deploy:
    needs: build
    name: Deploy Code to Production
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Code
        uses: actions/checkout@v3
      - name: Copy Code to Server
        uses: appleboy/ssh-action@master
        with:
          host: maxwelljoslyn.com
          username: maxwell
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_KEY_PASSPHRASE }}
          script: ls -la
          # script: git clone git@github.com:maxwelljoslyn/dnd.git /home/maxwell/dnd-copy
